apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: fdc
  name: gocode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gocode
  template:
    metadata:
      labels:
        app: gocode
    spec:
      imagePullSecrets:
        - name: pwz-secret
      containers:
        - name: gocode
          env:
            - name: ENV
              value: prod
          image: fdc123/gocode
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
          ports:
            - containerPort: 9000
